namespace SchoolMangementSystem
{
    partial class DashboardForm
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.Label titleLabel;
        private System.Windows.Forms.Label subtitleLabel;
        private System.Windows.Forms.Panel employeeCard;
        private System.Windows.Forms.Panel activeEmployeeCard;
        private System.Windows.Forms.Panel supervisorCard;
        private System.Windows.Forms.Panel activeSupervisorCard;
        private System.Windows.Forms.Label employeeCountValue;
        private System.Windows.Forms.Label activeEmployeeCountValue;
        private System.Windows.Forms.Label supervisorCountValue;
        private System.Windows.Forms.Label activeSupervisorCountValue;
        private System.Windows.Forms.Label employeeCountLabel;
        private System.Windows.Forms.Label activeEmployeeLabel;
        private System.Windows.Forms.Label supervisorCountLabel;
        private System.Windows.Forms.Label activeSupervisorLabel;
        private System.Windows.Forms.GroupBox recentEmployeesGroup;
        private System.Windows.Forms.ListBox recentEmployeesList;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.titleLabel = new System.Windows.Forms.Label();
            this.subtitleLabel = new System.Windows.Forms.Label();
            this.employeeCard = new System.Windows.Forms.Panel();
            this.employeeCountValue = new System.Windows.Forms.Label();
            this.employeeCountLabel = new System.Windows.Forms.Label();
            this.activeEmployeeCard = new System.Windows.Forms.Panel();
            this.activeEmployeeCountValue = new System.Windows.Forms.Label();
            this.activeEmployeeLabel = new System.Windows.Forms.Label();
            this.supervisorCard = new System.Windows.Forms.Panel();
            this.supervisorCountValue = new System.Windows.Forms.Label();
            this.supervisorCountLabel = new System.Windows.Forms.Label();
            this.activeSupervisorCard = new System.Windows.Forms.Panel();
            this.activeSupervisorCountValue = new System.Windows.Forms.Label();
            this.activeSupervisorLabel = new System.Windows.Forms.Label();
            this.recentEmployeesGroup = new System.Windows.Forms.GroupBox();
            this.recentEmployeesList = new System.Windows.Forms.ListBox();
            this.employeeCard.SuspendLayout();
            this.activeEmployeeCard.SuspendLayout();
            this.supervisorCard.SuspendLayout();
            this.activeSupervisorCard.SuspendLayout();
            this.recentEmployeesGroup.SuspendLayout();
            this.SuspendLayout();
            this.titleLabel.AutoSize = true;
            this.titleLabel.Font = new System.Drawing.Font("Tahoma", 20F);
            this.titleLabel.Location = new System.Drawing.Point(32, 28);
            this.titleLabel.Name = "titleLabel";
            this.titleLabel.Size = new System.Drawing.Size(231, 33);
            this.titleLabel.TabIndex = 0;
            this.titleLabel.Text = "Operations snapshot";
            this.subtitleLabel.AutoSize = true;
            this.subtitleLabel.Font = new System.Drawing.Font("Tahoma", 10F);
            this.subtitleLabel.ForeColor = System.Drawing.Color.DimGray;
            this.subtitleLabel.Location = new System.Drawing.Point(35, 70);
            this.subtitleLabel.Name = "subtitleLabel";
            this.subtitleLabel.Size = new System.Drawing.Size(126, 17);
            this.subtitleLabel.TabIndex = 1;
            this.subtitleLabel.Text = "Signed in as Admin";
            this.employeeCard.BackColor = System.Drawing.Color.White;
            this.employeeCard.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.employeeCard.Controls.Add(this.employeeCountValue);
            this.employeeCard.Controls.Add(this.employeeCountLabel);
            this.employeeCard.Location = new System.Drawing.Point(38, 112);
            this.employeeCard.Name = "employeeCard";
            this.employeeCard.Size = new System.Drawing.Size(180, 105);
            this.employeeCard.TabIndex = 2;
            this.employeeCountValue.AutoSize = true;
            this.employeeCountValue.Font = new System.Drawing.Font("Tahoma", 24F);
            this.employeeCountValue.Location = new System.Drawing.Point(17, 45);
            this.employeeCountValue.Name = "employeeCountValue";
            this.employeeCountValue.Size = new System.Drawing.Size(36, 39);
            this.employeeCountValue.TabIndex = 1;
            this.employeeCountValue.Text = "0";
            this.employeeCountLabel.AutoSize = true;
            this.employeeCountLabel.Font = new System.Drawing.Font("Tahoma", 10F);
            this.employeeCountLabel.Location = new System.Drawing.Point(18, 17);
            this.employeeCountLabel.Name = "employeeCountLabel";
            this.employeeCountLabel.Size = new System.Drawing.Size(112, 17);
            this.employeeCountLabel.TabIndex = 0;
            this.employeeCountLabel.Text = "Total employees";
            this.activeEmployeeCard.BackColor = System.Drawing.Color.White;
            this.activeEmployeeCard.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.activeEmployeeCard.Controls.Add(this.activeEmployeeCountValue);
            this.activeEmployeeCard.Controls.Add(this.activeEmployeeLabel);
            this.activeEmployeeCard.Location = new System.Drawing.Point(241, 112);
            this.activeEmployeeCard.Name = "activeEmployeeCard";
            this.activeEmployeeCard.Size = new System.Drawing.Size(180, 105);
            this.activeEmployeeCard.TabIndex = 3;
            this.activeEmployeeCountValue.AutoSize = true;
            this.activeEmployeeCountValue.Font = new System.Drawing.Font("Tahoma", 24F);
            this.activeEmployeeCountValue.Location = new System.Drawing.Point(17, 45);
            this.activeEmployeeCountValue.Name = "activeEmployeeCountValue";
            this.activeEmployeeCountValue.Size = new System.Drawing.Size(36, 39);
            this.activeEmployeeCountValue.TabIndex = 1;
            this.activeEmployeeCountValue.Text = "0";
            this.activeEmployeeLabel.AutoSize = true;
            this.activeEmployeeLabel.Font = new System.Drawing.Font("Tahoma", 10F);
            this.activeEmployeeLabel.Location = new System.Drawing.Point(18, 17);
            this.activeEmployeeLabel.Name = "activeEmployeeLabel";
            this.activeEmployeeLabel.Size = new System.Drawing.Size(122, 17);
            this.activeEmployeeLabel.TabIndex = 0;
            this.activeEmployeeLabel.Text = "Active employees";
            this.supervisorCard.BackColor = System.Drawing.Color.White;
            this.supervisorCard.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.supervisorCard.Controls.Add(this.supervisorCountValue);
            this.supervisorCard.Controls.Add(this.supervisorCountLabel);
            this.supervisorCard.Location = new System.Drawing.Point(444, 112);
            this.supervisorCard.Name = "supervisorCard";
            this.supervisorCard.Size = new System.Drawing.Size(180, 105);
            this.supervisorCard.TabIndex = 4;
            this.supervisorCountValue.AutoSize = true;
            this.supervisorCountValue.Font = new System.Drawing.Font("Tahoma", 24F);
            this.supervisorCountValue.Location = new System.Drawing.Point(17, 45);
            this.supervisorCountValue.Name = "supervisorCountValue";
            this.supervisorCountValue.Size = new System.Drawing.Size(36, 39);
            this.supervisorCountValue.TabIndex = 1;
            this.supervisorCountValue.Text = "0";
            this.supervisorCountLabel.AutoSize = true;
            this.supervisorCountLabel.Font = new System.Drawing.Font("Tahoma", 10F);
            this.supervisorCountLabel.Location = new System.Drawing.Point(18, 17);
            this.supervisorCountLabel.Name = "supervisorCountLabel";
            this.supervisorCountLabel.Size = new System.Drawing.Size(113, 17);
            this.supervisorCountLabel.TabIndex = 0;
            this.supervisorCountLabel.Text = "Total supervisors";
            this.activeSupervisorCard.BackColor = System.Drawing.Color.White;
            this.activeSupervisorCard.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.activeSupervisorCard.Controls.Add(this.activeSupervisorCountValue);
            this.activeSupervisorCard.Controls.Add(this.activeSupervisorLabel);
            this.activeSupervisorCard.Location = new System.Drawing.Point(647, 112);
            this.activeSupervisorCard.Name = "activeSupervisorCard";
            this.activeSupervisorCard.Size = new System.Drawing.Size(180, 105);
            this.activeSupervisorCard.TabIndex = 5;
            this.activeSupervisorCountValue.AutoSize = true;
            this.activeSupervisorCountValue.Font = new System.Drawing.Font("Tahoma", 24F);
            this.activeSupervisorCountValue.Location = new System.Drawing.Point(17, 45);
            this.activeSupervisorCountValue.Name = "activeSupervisorCountValue";
            this.activeSupervisorCountValue.Size = new System.Drawing.Size(36, 39);
            this.activeSupervisorCountValue.TabIndex = 1;
            this.activeSupervisorCountValue.Text = "0";
            this.activeSupervisorLabel.AutoSize = true;
            this.activeSupervisorLabel.Font = new System.Drawing.Font("Tahoma", 10F);
            this.activeSupervisorLabel.Location = new System.Drawing.Point(18, 17);
            this.activeSupervisorLabel.Name = "activeSupervisorLabel";
            this.activeSupervisorLabel.Size = new System.Drawing.Size(123, 17);
            this.activeSupervisorLabel.TabIndex = 0;
            this.activeSupervisorLabel.Text = "Active supervisors";
            this.recentEmployeesGroup.Controls.Add(this.recentEmployeesList);
            this.recentEmployeesGroup.Font = new System.Drawing.Font("Tahoma", 10F);
            this.recentEmployeesGroup.Location = new System.Drawing.Point(38, 250);
            this.recentEmployeesGroup.Name = "recentEmployeesGroup";
            this.recentEmployeesGroup.Size = new System.Drawing.Size(789, 274);
            this.recentEmployeesGroup.TabIndex = 6;
            this.recentEmployeesGroup.TabStop = false;
            this.recentEmployeesGroup.Text = "Recent employee activity";
            this.recentEmployeesList.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.recentEmployeesList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.recentEmployeesList.Font = new System.Drawing.Font("Tahoma", 10F);
            this.recentEmployeesList.FormattingEnabled = true;
            this.recentEmployeesList.ItemHeight = 16;
            this.recentEmployeesList.Location = new System.Drawing.Point(3, 20);
            this.recentEmployeesList.Name = "recentEmployeesList";
            this.recentEmployeesList.Size = new System.Drawing.Size(783, 251);
            this.recentEmployeesList.TabIndex = 0;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.WhiteSmoke;
            this.Controls.Add(this.recentEmployeesGroup);
            this.Controls.Add(this.activeSupervisorCard);
            this.Controls.Add(this.supervisorCard);
            this.Controls.Add(this.activeEmployeeCard);
            this.Controls.Add(this.employeeCard);
            this.Controls.Add(this.subtitleLabel);
            this.Controls.Add(this.titleLabel);
            this.Name = "DashboardForm";
            this.Size = new System.Drawing.Size(875, 575);
            this.employeeCard.ResumeLayout(false);
            this.employeeCard.PerformLayout();
            this.activeEmployeeCard.ResumeLayout(false);
            this.activeEmployeeCard.PerformLayout();
            this.supervisorCard.ResumeLayout(false);
            this.supervisorCard.PerformLayout();
            this.activeSupervisorCard.ResumeLayout(false);
            this.activeSupervisorCard.PerformLayout();
            this.recentEmployeesGroup.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
